### ISSUE TITLE
Some issues with space/tab markers

### ISSUE THREAD

**Issue by lucastrvsn** [somarlyonks/syme#4]
Hello. Thank you for this theme, really love it! But I'm having some trouble with spaces/tabs marker on lines. I'll attach one screenshot to illustrate.

![Screenshot](https://i.imgur.com/Hdoy2QP.png)

Those red dots is normal? If yes, how can I change?

Edit: `"editor.renderWhitespace": "boundary",` this is my config to show this dots.

Thank you in advance!

**Comment by somarlyonks** [comment]
Good point, that's even more terrible on rendering tabs.

![image](https://user-images.githubusercontent.com/29633025/71758921-7e048980-2ee0-11ea-93a2-d4a35fbb2c7a.png)

You may override the color with appending these to your settings:

```json
  "workbench.colorCustomizations": {
    "editorWhitespace.foreground": "#707cadaa"
  }
```

which made looks like this

![image](https://user-images.githubusercontent.com/29633025/71758942-e0f62080-2ee0-11ea-8ac3-01dc18b80eeb.png)

I think this is reasonable and like to publish a new update, it might take minutes.

**Comment by lucastrvsn** [comment]
Oh, I'm just about to make a PR! If you dont mind. Thanks! hahahah

**Comment by somarlyonks** [comment]
@lucastrvsn thanks anyway as a update has been published, you may update the theme in extensions or just customize the color as the comment before.

**Comment by lucastrvsn** [comment]
Thanks for the fast response!
